import { Segment } from './segment';

export type Content = {
  name: string;
  segments: Segment[];
};

const contents: Content[] = [
  {
    name: 'big_buck_bunny',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 4 },
      { index: 2, duration: 6 },
      {
        index: 3,
        duration: 4,
      },
      { index: 4, duration: 6 },
      { index: 5, duration: 4 },
      { index: 6, duration: 6 },
      {
        index: 7,
        duration: 4,
      },
      { index: 8, duration: 6 },
      { index: 9, duration: 4 },
      { index: 10, duration: 6 },
      {
        index: 11,
        duration: 4,
      },
      { index: 12, duration: 6 },
      { index: 13, duration: 4 },
      { index: 14, duration: 6 },
      {
        index: 15,
        duration: 4,
      },
      { index: 16, duration: 6 },
      { index: 17, duration: 4 },
      { index: 18, duration: 6 },
      {
        index: 19,
        duration: 4,
      },
      { index: 20, duration: 6 },
      { index: 21, duration: 4 },
      { index: 22, duration: 6 },
      {
        index: 23,
        duration: 4,
      },
      { index: 24, duration: 6 },
      { index: 25, duration: 4 },
      { index: 26, duration: 6 },
      {
        index: 27,
        duration: 4,
      },
      { index: 28, duration: 6 },
      { index: 29, duration: 4 },
      { index: 30, duration: 6 },
      {
        index: 31,
        duration: 4,
      },
      { index: 32, duration: 6 },
      { index: 33, duration: 4 },
      { index: 34, duration: 6 },
      {
        index: 35,
        duration: 4,
      },
      { index: 36, duration: 6 },
      { index: 37, duration: 4 },
      { index: 38, duration: 6 },
      {
        index: 39,
        duration: 4,
      },
      { index: 40, duration: 6 },
      { index: 41, duration: 4 },
      { index: 42, duration: 6 },
      {
        index: 43,
        duration: 4,
      },
      { index: 44, duration: 6 },
      { index: 45, duration: 4 },
      { index: 46, duration: 6 },
      {
        index: 47,
        duration: 4,
      },
      { index: 48, duration: 6 },
      { index: 49, duration: 4 },
      { index: 50, duration: 6 },
      {
        index: 51,
        duration: 4,
      },
      { index: 52, duration: 6 },
      { index: 53, duration: 4 },
      { index: 54, duration: 6 },
      {
        index: 55,
        duration: 4,
      },
      { index: 56, duration: 6 },
      { index: 57, duration: 4 },
      { index: 58, duration: 6 },
      {
        index: 59,
        duration: 4,
      },
      { index: 60, duration: 6 },
      { index: 61, duration: 4 },
      { index: 62, duration: 6 },
      {
        index: 63,
        duration: 4,
      },
      { index: 64, duration: 6 },
      { index: 65, duration: 4 },
      { index: 66, duration: 6 },
      {
        index: 67,
        duration: 4,
      },
      { index: 68, duration: 6 },
      { index: 69, duration: 4 },
      { index: 70, duration: 6 },
      {
        index: 71,
        duration: 4,
      },
      { index: 72, duration: 6 },
      { index: 73, duration: 4 },
      { index: 74, duration: 6 },
      {
        index: 75,
        duration: 4,
      },
      { index: 76, duration: 6 },
      { index: 77, duration: 4 },
      { index: 78, duration: 6 },
      {
        index: 79,
        duration: 4,
      },
      { index: 80, duration: 6 },
      { index: 81, duration: 4 },
      { index: 82, duration: 6 },
      {
        index: 83,
        duration: 4,
      },
      { index: 84, duration: 6 },
      { index: 85, duration: 4 },
      { index: 86, duration: 6 },
      {
        index: 87,
        duration: 4,
      },
      { index: 88, duration: 6 },
      { index: 89, duration: 4 },
      { index: 90, duration: 6 },
      {
        index: 91,
        duration: 4,
      },
      { index: 92, duration: 6 },
      { index: 93, duration: 4 },
      { index: 94, duration: 6 },
      {
        index: 95,
        duration: 4,
      },
      { index: 96, duration: 6 },
      { index: 97, duration: 4 },
      { index: 98, duration: 6 },
      {
        index: 99,
        duration: 4,
      },
      { index: 100, duration: 6 },
      { index: 101, duration: 4 },
      { index: 102, duration: 6 },
      {
        index: 103,
        duration: 4,
      },
      { index: 104, duration: 6 },
      { index: 105, duration: 4 },
      { index: 106, duration: 6 },
      {
        index: 107,
        duration: 4,
      },
      { index: 108, duration: 6 },
      { index: 109, duration: 4 },
      { index: 110, duration: 6 },
      {
        index: 111,
        duration: 4,
      },
      { index: 112, duration: 6 },
      { index: 113, duration: 4 },
      { index: 114, duration: 6 },
      {
        index: 115,
        duration: 4,
      },
      { index: 116, duration: 6 },
      { index: 117, duration: 4 },
      { index: 118, duration: 6 },
      {
        index: 119,
        duration: 0.458333,
      },
    ],
  },
  {
    name: 'start',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 1.041667 },
    ],
  },
  {
    name: 'end',
    segments: [
      {
        index: 0,
        duration: 6,
      },
      {
        index: 1,
        duration: 1.041667,
      },
    ],
  },
  {
    name: 'offline',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 1.041667 },
    ],
  },
  {
    name: 'brb',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 1.041667 },
    ],
  },
  {
    name: 'countdown60',
    segments: [
      { index: 0, duration: 6.006 },
      { index: 1, duration: 4.004 },
      {
        index: 2,
        duration: 6.006,
      },
      { index: 3, duration: 4.004 },
      { index: 4, duration: 6.006 },
      {
        index: 5,
        duration: 4.004,
      },
      { index: 6, duration: 6.006 },
      { index: 7, duration: 4.004 },
      {
        index: 8,
        duration: 6.006,
      },
      { index: 9, duration: 4.004 },
      { index: 10, duration: 6.006 },
      {
        index: 11,
        duration: 4.004,
      },
      { index: 12, duration: 6.006 },
      { index: 13, duration: 1.001 },
    ],
  },
  {
    name: 'start60',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 4 },
      { index: 2, duration: 6 },
      { index: 3, duration: 4 },
      { index: 4, duration: 6 },
      { index: 5, duration: 4 },
      { index: 6, duration: 6 },
      { index: 7, duration: 4 },
      { index: 8, duration: 6 },
      { index: 9, duration: 4 },
      { index: 10, duration: 6 },
      { index: 11, duration: 4 },
      { index: 12, duration: 0.041667 },
    ],
  },
  {
    name: 'end60',
    segments: [
      { index: 0, duration: 6 },
      { index: 1, duration: 4 },
      { index: 2, duration: 6 },
      { index: 3, duration: 4 },
      { index: 4, duration: 6 },
      { index: 5, duration: 4 },
      { index: 6, duration: 6 },
      { index: 7, duration: 4 },
      { index: 8, duration: 6 },
      { index: 9, duration: 4 },
      { index: 10, duration: 6 },
      { index: 11, duration: 4 },
      { index: 12, duration: 0.041667 },
    ],
  },
];

export const getContentByName = (name: string) =>
  contents.find((content) => content.name === name);
